import { tools } from '../data/tools';
import { websiteSchema, faqSchema } from '../utils/seo';

const faqs = [
  { question: 'Do image files upload to a server?', answer: 'Most tools process images directly in your browser using canvas and file APIs. Placeholder tools clearly say when extra integration is needed.' },
  { question: 'Which formats are supported?', answer: 'Common browser-supported formats such as JPG, PNG, WebP, BMP, and GIF can be opened, with export options varying by tool.' },
  { question: 'Is Image Tools free?', answer: 'Yes. The website is designed as a free utility collection for everyday image tasks.' },
  { question: 'Can I use it on a phone?', answer: 'Yes. The interface is responsive and works on modern mobile browsers.' },
];

export function homePage() {
  const featured = tools.filter((tool) => ['image-compressor', 'image-resizer', 'image-cropper', 'image-converter', 'image-to-pdf', 'background-remover'].includes(tool.slug));
  return {
    seo: { title: 'Free Online Image Tools | Compress, Resize, Convert Images', description: 'Fast, privacy-friendly image tools for compressing, resizing, converting, cropping, and optimizing images in your browser.', path: '/', jsonLd: [websiteSchema(), faqSchema(faqs)] },
    html: `<section class="hero site-container"><div class="hero-grid"><div><span class="eyebrow"><i class="fa-solid fa-bolt" aria-hidden="true"></i> Fast browser image utilities</span><h1>Free Online Image Tools</h1><p class="lead">Compress, resize, convert, crop, and optimize images directly in your browser with polished tools built for speed, privacy, and everyday use.</p><div class="actions"><a data-link class="btn btn-primary" href="/image-compressor">Start With Image Compressor <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a><a data-link class="btn btn-secondary" href="/tools">View All Tools</a></div><div class="trust-row"><span><i class="fa-solid fa-shield-halved" aria-hidden="true"></i> No upload required for many tools</span><span><i class="fa-solid fa-bolt" aria-hidden="true"></i> Fast browser processing</span><span><i class="fa-solid fa-check" aria-hidden="true"></i> Free to use</span><span><i class="fa-solid fa-mobile-screen-button" aria-hidden="true"></i> Mobile friendly</span></div></div><aside class="mock-panel" aria-label="Image tool preview"><div class="mock-preview"><i class="fa-regular fa-file-image" aria-hidden="true"></i></div><div class="mock-line"></div><div class="mock-line w70"></div><div class="mock-stats"><div><strong>2.8 MB</strong><br>Original</div><div><strong>940 KB</strong><br>Output</div><div><strong>67%</strong><br>Saved</div></div></aside></div></section>${section('Featured Tools', 'Start with the most common image tasks.', cards(featured))}${howItWorks()}${features()}${section('Popular Image Tools', 'Explore more browser-based workflows.', cards(tools.slice(6, 14), 'grid-4'))}${privacy()}${faqPreview()}<section class="section site-container"><div class="cta-band"><h2>Ready to edit an image?</h2><p>Choose a tool, process your file locally where possible, and download the optimized result.</p><div class="actions"><a data-link class="btn btn-secondary" href="/tools">Open All Image Tools <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div></div></section>`
  };
}

function section(title: string, intro: string, body: string) { return `<section class="section site-container"><div class="section-head"><div><h2>${title}</h2><p class="lead">${intro}</p></div><a data-link class="card-link" href="/tools">All tools <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div>${body}</section>`; }
function cards(items = tools, grid = 'grid-3') { return `<div class="grid ${grid}">${items.map((tool) => `<article class="card"><span class="icon-box"><i class="fa-solid ${tool.icon.includes(' ') ? 'fa-image' : tool.icon}" aria-hidden="true"></i></span><h3>${tool.name}</h3><p>${tool.description}</p><a data-link class="card-link" href="/${tool.slug}">Open tool <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></article>`).join('')}</div>`; }
function howItWorks() { return section('How It Works', 'A simple flow for quick image tasks.', `<div class="grid grid-4">${['Upload or drop your image', 'Choose settings', 'Process in your browser', 'Download the result'].map((step, index) => `<article class="card"><span class="badge">Step ${index + 1}</span><h3>${step}</h3><p>Clear controls guide you from file selection to a ready-to-use output.</p></article>`).join('')}</div>`); }
function features() { const items = [['fa-shield-halved','Private by design'],['fa-bolt','Fast processing'],['fa-mobile-screen-button','Works on mobile'],['fa-download','No software install'],['fa-layer-group','Multiple image formats'],['fa-check','Clean optimized output']]; return section('Built For Daily Image Work', 'Helpful details that keep the experience smooth.', `<div class="grid grid-3">${items.map(([icon,title]) => `<article class="card"><span class="icon-box"><i class="fa-solid ${icon}" aria-hidden="true"></i></span><h3>${title}</h3><p>Focused controls, responsive layouts, and clear status messages make each tool easy to use.</p></article>`).join('')}</div>`); }
function privacy() { return `<section class="section site-container"><div class="cta-band"><span class="eyebrow"><i class="fa-solid fa-shield-halved" aria-hidden="true"></i> Privacy note</span><h2>Local processing whenever possible</h2><p>Many image operations use browser APIs such as canvas and Blob export. That means routine compression, resizing, conversion, enhancement, watermarking, and metadata cleanup can happen on your device without a server upload.</p></div></section>`; }
function faqPreview() { return `<section class="section site-container"><div class="section-head"><div><h2>Common Questions</h2><p class="lead">Quick answers before you start.</p></div><a data-link class="card-link" href="/faq">Full FAQ <i class="fa-solid fa-circle-question" aria-hidden="true"></i></a></div>${faqs.map((item) => `<article class="faq-item"><h3>${item.question}</h3><p>${item.answer}</p></article>`).join('')}</section>`; }
