import { tools } from '../data/tools';
import { websiteSchema, faqSchema } from '../utils/seo';

const wrap = 'ui-container';
const card = 'ui-card';

const faqs = [
  { question: 'Do image files upload to a server?', answer: 'Most tools process images directly in your browser using canvas and file APIs. Placeholder tools clearly say when extra integration is needed.' },
  { question: 'Which formats are supported?', answer: 'Common browser-supported formats such as JPG, PNG, WebP, BMP, and GIF can be opened, with export options varying by tool.' },
  { question: 'Is Image Tools free?', answer: 'Yes. The website is designed as a free utility collection for everyday image tasks.' },
  { question: 'Can I use it on a phone?', answer: 'Yes. The interface is responsive and works on modern mobile browsers.' },
];

export function homePage() {
  const featured = tools.filter((tool) => ['image-compressor', 'image-resizer', 'image-cropper', 'image-converter', 'image-to-pdf', 'background-remover'].includes(tool.slug));
  return {
    seo: { title: 'Free Online Image Tools | Compress, Resize, Convert Images', description: 'Fast, privacy-friendly image tools for compressing, resizing, converting, cropping, and optimizing images in your browser.', path: '/', jsonLd: [websiteSchema(), faqSchema(faqs)] },
    html: `<section class="ui-section"><div class="${wrap}"><div class="grid grid-cols-1 items-center gap-8 lg:grid-cols-2"><div><span class="ui-kicker"><i class="fa-solid fa-bolt" aria-hidden="true"></i> Fast browser image utilities</span><h1 class="mt-5 text-4xl font-semibold tracking-tight text-gray-900 md:text-5xl">Free Online Image Tools</h1><p class="ui-lead mt-4 max-w-2xl md:text-lg">Compress, resize, convert, crop, and optimize images directly in your browser with polished tools built for speed, privacy, and everyday use.</p><div class="mt-6 flex flex-col gap-3 sm:flex-row"><a data-link class="btn btn-primary" href="/image-compressor">Start With Image Compressor <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a><a data-link class="btn btn-secondary" href="/tools">View All Tools</a></div><div class="mt-6 flex flex-wrap gap-2">${['No upload required for many tools','Fast browser processing','Free to use','Mobile friendly'].map((item) => `<span class="ui-badge bg-white text-gray-600"><i class="fa-solid fa-check text-indigo-600" aria-hidden="true"></i> ${item}</span>`).join('')}</div></div><aside class="${card} space-y-4" aria-label="Image tool preview"><div class="preview-box border-indigo-200 bg-indigo-50 text-5xl text-indigo-600"><i class="fa-regular fa-file-image" aria-hidden="true"></i></div><div class="h-3 rounded-full bg-gray-200"></div><div class="h-3 w-2/3 rounded-full bg-gray-200"></div><div class="grid grid-cols-1 gap-3 sm:grid-cols-3"><div class="result-box"><strong class="block text-gray-900">2.8 MB</strong><span class="text-sm text-gray-500">Original</span></div><div class="result-box"><strong class="block text-gray-900">940 KB</strong><span class="text-sm text-gray-500">Output</span></div><div class="result-box"><strong class="block text-gray-900">67%</strong><span class="text-sm text-gray-500">Saved</span></div></div></aside></div></div></section>${sectionBlock('Featured Tools', 'Start with the most common image tasks.', cards(featured))}${howItWorks()}${features()}${sectionBlock('Popular Image Tools', 'Explore more browser-based workflows.', cards(tools.slice(6, 14)))}${privacy()}${faqPreview()}<section class="ui-section"><div class="${wrap}"><div class="ui-card border-indigo-200 bg-indigo-50"><h2 class="ui-section-title">Ready to edit an image?</h2><p class="ui-text mt-3 text-gray-600">Choose a tool, process your file locally where possible, and download the optimized result.</p><a data-link class="btn btn-secondary mt-5" href="/tools">Open All Image Tools <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div></div></section>`
  };
}

function sectionBlock(title: string, intro: string, body: string) { return `<section class="ui-section"><div class="${wrap}"><div class="mb-6 flex flex-col gap-4 md:flex-row md:items-end md:justify-between"><div><h2 class="ui-section-title">${title}</h2><p class="ui-text mt-2">${intro}</p></div><a data-link class="text-sm font-semibold text-indigo-700 hover:text-indigo-900" href="/tools">All tools <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></div>${body}</div></section>`; }
function cards(items = tools) { return `<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">${items.map((tool) => `<article class="${card} flex min-h-full flex-col gap-3"><span class="inline-flex h-10 w-10 items-center justify-center rounded-xl border border-indigo-200 bg-indigo-50 text-indigo-600"><i class="fa-solid ${tool.icon.includes(' ') ? 'fa-image' : tool.icon}" aria-hidden="true"></i></span><h3 class="text-lg font-semibold text-gray-900">${tool.name}</h3><p class="ui-text">${tool.description}</p><a data-link class="mt-auto text-sm font-semibold text-indigo-700 hover:text-indigo-900" href="/${tool.slug}">Open tool <i class="fa-solid fa-arrow-right" aria-hidden="true"></i></a></article>`).join('')}</div>`; }
function howItWorks() { return sectionBlock('How It Works', 'A simple flow for quick image tasks.', `<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-4">${['Upload or drop your image', 'Choose settings', 'Process in your browser', 'Download the result'].map((step, index) => `<article class="${card} space-y-3"><span class="ui-badge text-xs">Step ${index + 1}</span><h3 class="text-lg font-semibold text-gray-900">${step}</h3><p class="ui-text">Clear controls guide you from file selection to a ready-to-use output.</p></article>`).join('')}</div>`); }
function features() { const items = [['fa-shield-halved','Private by design'],['fa-bolt','Fast processing'],['fa-mobile-screen-button','Works on mobile'],['fa-download','No software install'],['fa-layer-group','Multiple image formats'],['fa-check','Clean optimized output']]; return sectionBlock('Built For Daily Image Work', 'Helpful details that keep the experience smooth.', `<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">${items.map(([icon,title]) => `<article class="${card} space-y-3"><span class="inline-flex h-10 w-10 items-center justify-center rounded-xl border border-indigo-200 bg-indigo-50 text-indigo-600"><i class="fa-solid ${icon}" aria-hidden="true"></i></span><h3 class="text-lg font-semibold text-gray-900">${title}</h3><p class="ui-text">Focused controls, responsive layouts, and clear status messages make each tool easy to use.</p></article>`).join('')}</div>`); }
function privacy() { return `<section class="ui-section"><div class="${wrap}"><div class="${card}"><span class="ui-kicker"><i class="fa-solid fa-shield-halved" aria-hidden="true"></i> Privacy note</span><h2 class="ui-section-title mt-4">Local processing whenever possible</h2><p class="ui-text mt-3">Many image operations use browser APIs such as canvas and Blob export. That means routine compression, resizing, conversion, enhancement, watermarking, and metadata cleanup can happen on your device without a server upload.</p></div></div></section>`; }
function faqPreview() { return `<section class="ui-section"><div class="${wrap}"><div class="mb-6 flex items-end justify-between gap-4"><div><h2 class="ui-section-title">Common Questions</h2><p class="ui-text mt-2">Quick answers before you start.</p></div><a data-link class="text-sm font-semibold text-indigo-700" href="/faq">Full FAQ</a></div><div class="space-y-4">${faqs.map((item) => `<article class="ui-card"><h3 class="font-semibold text-gray-900">${item.question}</h3><p class="ui-text mt-2">${item.answer}</p></article>`).join('')}</div></div></section>`; }
