import { faqSchema } from '../utils/seo';

export const faqItems = [
  { question: 'Are images processed locally?', answer: 'Most implemented tools use browser APIs to process images directly on your device. Tools that need future integrations are clearly labeled.' },
  { question: 'Why do some outputs look different?', answer: 'Canvas export may flatten transparency for JPG and can vary slightly between browsers.' },
  { question: 'What is the maximum file size?', answer: 'The app warns above 30 MB because very large images can stress mobile browsers.' },
  { question: 'Can I deploy this to Cloudflare Pages?', answer: 'Yes. Build with npm run build and deploy the dist directory from a GitHub repository.' },
  { question: 'Does metadata removal remove all EXIF data?', answer: 'Canvas re-encoding strips most embedded metadata, but specialized forensic workflows may need dedicated desktop tools.' },
];

export function aboutPage() { return basic('About Image Tools', 'About Image Tools', 'Image Tools is a free collection of lightweight image utilities built for practical browser-side workflows. The project focuses on speed, clean design, and accurate privacy messaging.', '/about', `<div class="grid grid-3"><article class="card"><h3>Fast</h3><p>Static hosting and browser APIs keep the experience responsive.</p></article><article class="card"><h3>Privacy-aware</h3><p>Many operations happen locally without intentional file storage.</p></article><article class="card"><h3>Deployable</h3><p>The app is ready for GitHub and Cloudflare Pages.</p></article></div>`); }
export function contactPage() { return basic('Contact Image Tools', 'Contact', 'Send bug reports, feature suggestions, and website questions.', '/contact', `<div class="grid grid-3"><article class="card"><span class="icon-box"><i class="fa-solid fa-envelope" aria-hidden="true"></i></span><h3>Email</h3><p>support@itisuniqueofficial.com</p></article><article class="card"><h3>Bug reports</h3><p>Include your browser, file type, and the steps that caused the issue.</p></article><article class="card"><h3>Feature suggestions</h3><p>Share the image workflows you would like added next.</p></article></div><form class="tool-panel" aria-label="Contact form placeholder"><div class="field"><label for="name">Name</label><input id="name" type="text"></div><div class="field"><label for="email">Email</label><input id="email" type="email"></div><div class="field"><label for="message">Message</label><textarea id="message" rows="5"></textarea></div><p class="notice">This static form is ready for a form backend or Cloudflare integration.</p></form>`); }
export function privacyPage() { return basic('Privacy Policy | Image Tools', 'Privacy Policy', 'This policy explains how Image Tools approaches browser-side files and third-party resources.', '/privacy', `<div class="tool-panel"><h2>Browser-side processing</h2><p>Most tools process images directly in your browser using APIs such as canvas, Blob, FileReader, and object URLs.</p><h2>File storage</h2><p>Files are not intentionally stored by this website. If a future feature requires upload processing, it should be clearly disclosed on that tool page.</p><h2>Third-party libraries</h2><p>Font Awesome and Tailwind CSS are loaded from CDN resources. Image to PDF uses a client-side PDF library bundled with the app.</p><h2>Analytics</h2><p>Analytics may be added later. If added, this policy should be updated to describe the provider and data collected.</p><h2>Contact</h2><p>Questions can be sent to support@itisuniqueofficial.com.</p></div>`); }
export function termsPage() { return basic('Terms of Use | Image Tools', 'Terms of Use', 'Use Image Tools responsibly and verify important outputs before publishing or distributing them.', '/terms', `<div class="tool-panel"><h2>Use of service</h2><p>Image Tools is provided for general utility use without warranties. You are responsible for the files you process and download.</p><h2>No sensitive reliance</h2><p>Do not rely on browser tools as the only copy of important files. Keep backups before processing.</p><h2>Placeholder features</h2><p>Some pages are prepared for future integrations and do not claim working conversion or AI behavior.</p></div>`); }
export function faqPage() { return { seo: { title: 'FAQ | Image Tools', description: 'Answers about browser image processing, supported formats, privacy, deployment, and metadata cleanup.', path: '/faq', jsonLd: faqSchema(faqItems) }, html: `<section class="page-hero site-container"><span class="eyebrow"><i class="fa-solid fa-circle-question" aria-hidden="true"></i> Help center</span><h1>FAQ</h1><p class="lead">Answers to common questions about Image Tools.</p></section><section class="section site-container">${faqItems.map((item) => `<article class="faq-item"><h3>${item.question}</h3><p>${item.answer}</p></article>`).join('')}</section>`}; }
export function notFoundPage() { return basic('Page Not Found | Image Tools', 'Page Not Found', 'The page you requested could not be found.', '/404', `<a data-link class="btn btn-primary" href="/tools">Browse Image Tools</a>`); }

function basic(title: string, h1: string, intro: string, path: string, body: string) { return { seo: { title, description: intro, path }, html: `<section class="page-hero site-container"><span class="eyebrow"><i class="fa-solid fa-circle-info" aria-hidden="true"></i> Image Tools</span><h1>${h1}</h1><p class="lead">${intro}</p></section><section class="section site-container">${body}</section>`}; }
