import { faqSchema } from '../utils/seo';

const wrap = 'ui-container';
const card = 'ui-card';

export const faqItems = [
  { question: 'Are images processed locally?', answer: 'Most implemented tools use browser APIs to process images directly on your device. Tools that need future integrations are clearly labeled.' },
  { question: 'Why do some outputs look different?', answer: 'Canvas export may flatten transparency for JPG and can vary slightly between browsers.' },
  { question: 'What is the maximum file size?', answer: 'The app warns above 30 MB because very large images can stress mobile browsers.' },
  { question: 'Can I deploy this to Cloudflare Pages?', answer: 'Yes. Build with npm run build and deploy the dist directory from a GitHub repository.' },
  { question: 'Does metadata removal remove all EXIF data?', answer: 'Canvas re-encoding strips most embedded metadata, but specialized forensic workflows may need dedicated desktop tools.' },
];

export function aboutPage() { return basic('About Image Tools', 'About Image Tools', 'Image Tools is a free collection of lightweight image utilities built for practical browser-side workflows. The project focuses on speed, clean design, and accurate privacy messaging.', '/about', `<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"><article class="${card}"><h3 class="text-lg font-semibold text-gray-900">Fast</h3><p class="ui-text mt-2">Static hosting and browser APIs keep the experience responsive.</p></article><article class="${card}"><h3 class="text-lg font-semibold text-gray-900">Privacy-aware</h3><p class="ui-text mt-2">Many operations happen locally without intentional file storage.</p></article><article class="${card}"><h3 class="text-lg font-semibold text-gray-900">Deployable</h3><p class="ui-text mt-2">The app is ready for GitHub and Cloudflare Pages.</p></article></div>`); }
export function contactPage() { return basic('Contact Image Tools', 'Contact', 'Send bug reports, feature suggestions, and website questions.', '/contact', `<div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"><article class="${card}"><h3 class="text-lg font-semibold text-gray-900"><i class="fa-solid fa-envelope text-indigo-600" aria-hidden="true"></i> Email</h3><p class="mt-2 text-sm text-gray-500">support@itisuniqueofficial.com</p></article><article class="${card}"><h3 class="text-lg font-semibold text-gray-900">Bug reports</h3><p class="mt-2 text-sm leading-6 text-gray-500">Include your browser, file type, and the steps that caused the issue.</p></article><article class="${card}"><h3 class="text-lg font-semibold text-gray-900">Feature suggestions</h3><p class="mt-2 text-sm leading-6 text-gray-500">Share the image workflows you would like added next.</p></article></div><form class="mt-6 ${card} space-y-5" aria-label="Contact form placeholder"><div><label class="mb-2 block text-sm font-medium text-gray-600" for="name">Name</label><input class="h-11 w-full rounded-xl border border-gray-200 px-4 text-sm focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-100" id="name" type="text"></div><div><label class="mb-2 block text-sm font-medium text-gray-600" for="email">Email</label><input class="h-11 w-full rounded-xl border border-gray-200 px-4 text-sm focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-100" id="email" type="email"></div><div><label class="mb-2 block text-sm font-medium text-gray-600" for="message">Message</label><textarea class="w-full rounded-xl border border-gray-200 px-4 py-3 text-sm focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-100" id="message" rows="5"></textarea></div><p class="rounded-xl border border-indigo-100 bg-indigo-50 px-4 py-3 text-sm text-gray-600">This static form is ready for a form backend or Cloudflare integration.</p></form>`); }
export function privacyPage() { return basic('Privacy Policy | Image Tools', 'Privacy Policy', 'This policy explains how Image Tools approaches browser-side files and third-party resources.', '/privacy', policy(['Browser-side processing|Most tools process images directly in your browser using APIs such as canvas, Blob, FileReader, and object URLs.', 'File storage|Files are not intentionally stored by this website. If a future feature requires upload processing, it should be clearly disclosed on that tool page.', 'Third-party libraries|Font Awesome, Tailwind CSS, Cropper.js, and pdf.js may load from CDN resources. Image to PDF uses a client-side PDF library bundled with the app.', 'Analytics|Analytics may be added later. If added, this policy should be updated to describe the provider and data collected.', 'Contact|Questions can be sent to support@itisuniqueofficial.com.'])); }
export function termsPage() { return basic('Terms of Use | Image Tools', 'Terms of Use', 'Use Image Tools responsibly and verify important outputs before publishing or distributing them.', '/terms', policy(['Use of service|Image Tools is provided for general utility use without warranties. You are responsible for the files you process and download.', 'No sensitive reliance|Do not rely on browser tools as the only copy of important files. Keep backups before processing.', 'Placeholder features|Some pages are prepared for future integrations and do not claim working conversion or AI behavior.'])); }
export function faqPage() { return { seo: { title: 'FAQ | Image Tools', description: 'Answers about browser image processing, supported formats, privacy, deployment, and metadata cleanup.', path: '/faq', jsonLd: faqSchema(faqItems) }, html: `<section class="ui-section"><div class="${wrap}"><span class="ui-kicker"><i class="fa-solid fa-circle-question" aria-hidden="true"></i> Help center</span><h1 class="ui-page-title mt-5">FAQ</h1><p class="ui-lead mt-3 max-w-2xl">Answers to common questions about Image Tools.</p></div></section><section class="pb-14"><div class="${wrap}"><div class="space-y-4">${faqItems.map((item) => `<article class="ui-card"><h3 class="font-semibold text-gray-900">${item.question}</h3><p class="ui-text mt-2">${item.answer}</p></article>`).join('')}</div></div></section>`}; }
export function notFoundPage() { return basic('Page Not Found | Image Tools', 'Page Not Found', 'The page you requested could not be found.', '/404', `<a data-link class="inline-flex h-11 items-center justify-center rounded-xl border border-indigo-600 bg-indigo-600 px-5 text-sm font-semibold text-white hover:bg-indigo-700" href="/tools">Browse Image Tools</a>`); }

function policy(items: string[]) { return `<div class="${card} space-y-6">${items.map((item) => { const [title, text] = item.split('|'); return `<section><h2 class="text-xl font-semibold text-gray-900">${title}</h2><p class="ui-text mt-2">${text}</p></section>`; }).join('')}</div>`; }
function basic(title: string, h1: string, intro: string, path: string, body: string) { return { seo: { title, description: intro, path }, html: `<section class="ui-section"><div class="${wrap}"><span class="ui-kicker"><i class="fa-solid fa-circle-info" aria-hidden="true"></i> Image Tools</span><h1 class="ui-page-title mt-5">${h1}</h1><p class="ui-lead mt-3 max-w-2xl">${intro}</p></div></section><section class="pb-14"><div class="${wrap}">${body}</div></section>`}; }
