import { getTool, relatedTools } from '../data/tools';
import { appSchema, faqSchema } from '../utils/seo';

const wrap = 'ui-container';
const section = 'ui-section';
const card = 'ui-card';
const h2 = 'ui-section-title mb-5';
const btnPrimary = 'btn btn-primary';
const btnSecondary = 'btn btn-secondary';

export function toolPage(slug: string) {
  const tool = getTool(slug); if (!tool) return null;
  const faqs = [{ question: `How does ${tool.name} work?`, answer: tool.implemented ? 'The tool uses browser APIs where possible so the file can be processed on your device.' : 'This page is prepared for a future client-side integration and does not currently perform the final operation.' }, { question: 'Are files intentionally stored?', answer: 'No. This static website does not intentionally store your selected files.' }];
  return { seo: { title: `${tool.name} | Free Online Image Tool`, description: tool.description, path: `/${slug}`, jsonLd: [appSchema(tool.name, tool.description, `/${slug}`), faqSchema(faqs)] }, html: `<section class="${section}"><div class="${wrap}"><div class="max-w-3xl"><span class="inline-flex h-12 w-12 items-center justify-center rounded-2xl border border-indigo-200 bg-indigo-50 text-indigo-600"><i class="fa-solid ${tool.icon.includes(' ') ? 'fa-image' : tool.icon}" aria-hidden="true"></i></span><h1 class="ui-page-title mt-5">${tool.name}</h1><p class="ui-lead mt-3">${tool.description}</p><div class="mt-5 flex flex-wrap gap-2"><span class="ui-badge bg-white text-gray-600"><i class="fa-solid fa-shield-halved text-indigo-600" aria-hidden="true"></i> Privacy-aware workflow</span><span class="ui-badge bg-white text-gray-600"><i class="fa-solid fa-bolt text-indigo-600" aria-hidden="true"></i> Browser-friendly</span><span class="ui-badge bg-white text-gray-600"><i class="fa-solid fa-mobile-screen-button text-indigo-600" aria-hidden="true"></i> Responsive UI</span></div></div></div></section>${panel(slug)}${info(slug, tool.name, faqs)}` };
}

function panel(slug: string) {
  if (slug === 'pdf-to-image') return pdfToImagePanel();
  if (slug === 'background-remover') return placeholder('AI background removal is prepared for future integration.');
  if (slug === 'image-to-pdf') return `<section class="${section}"><div class="${wrap}"><div class="${card} tool-panel" data-tool-root><h2 class="${h2}">Main Tool Panel</h2>${dropzone('fa-file-image', 'Upload or drop images', 'JPG, PNG, or WebP', true)}<ul data-file-list class="alert-box"><li>No images selected</li></ul><div class="settings-grid"><div class="field-group"><label for="page-size" class="field-label">Page size</label><select id="page-size" class="tool-control"><option value="auto">Auto</option><option value="a4">A4</option><option value="letter">Letter</option></select><p class="field-helper">Choose the PDF page size used for exported pages.</p></div><div class="action-group field-group-full"><button class="${btnPrimary}" data-action disabled>Generate PDF</button></div></div><p class="text-sm font-medium text-indigo-700" data-status aria-live="polite">Choose images to begin.</p></div></div></section>`;
  return `<section class="${section}"><div class="${wrap}"><div class="tool-layout" data-tool-root><div class="${card} tool-panel"><h2 class="${h2}">Main Tool Panel</h2>${dropzone('fa-image', 'Upload or drop your image', 'Accepted formats depend on this tool')}<p class="alert-box" data-file-name>No file selected</p>${settings(slug)}<div class="action-group"><button class="${btnPrimary}" data-action disabled>Process Image</button><button class="${btnSecondary}" data-download disabled><i class="fa-solid fa-download" aria-hidden="true"></i> Download</button><button class="${btnSecondary}" data-reset>Reset</button></div><p class="text-sm font-medium text-indigo-700" data-status aria-live="polite">Choose an image to begin.</p><div class="grid grid-cols-1 gap-3 sm:grid-cols-3" data-stats><div class="result-box"><strong class="block text-gray-900">-</strong><span class="text-sm text-gray-500">Original</span></div><div class="result-box"><strong class="block text-gray-900">-</strong><span class="text-sm text-gray-500">Output</span></div><div class="result-box"><strong class="block text-gray-900">-</strong><span class="text-sm text-gray-500">Result</span></div></div></div><aside class="${card} tool-panel"><h2 class="${h2}">Preview</h2><div class="preview-box ${slug === 'image-cropper' ? 'cropper-wrap' : ''}" data-source-preview><span class="text-sm text-gray-500">Selected image preview</span></div><div class="preview-box" data-preview><span class="text-sm text-gray-500">Output preview will appear here</span></div></aside></div></div></section>`;
}

function settings(slug: string) {
  const map: Record<string, string> = {
    'image-compressor': `<div class="settings-grid"><div class="field-group"><label class="field-label" for="quality">Quality percentage</label><input class="range-control" id="quality" type="range" min="10" max="100" value="78"><p class="field-helper">Lower quality usually creates a smaller file.</p></div><div class="field-group"><label class="field-label" for="format">Output format</label><select class="tool-control" id="format"><option value="same">Same as input</option><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select><p class="field-helper">WebP is often smaller when supported.</p></div></div>`,
    'image-resizer': `<div class="settings-grid"><div class="field-group"><label class="field-label" for="width">Width</label><input class="tool-control" id="width" type="number" min="1"><p class="field-helper">Output width in pixels.</p></div><div class="field-group"><label class="field-label" for="height">Height</label><input class="tool-control" id="height" type="number" min="1"><p class="field-helper">Output height in pixels.</p></div><label class="option-box"><input id="ratio" type="checkbox" checked><span><strong class="block text-gray-900">Maintain aspect ratio</strong><span class="block text-gray-600">Automatically update the other dimension when one value changes.</span></span></label></div>`,
    'image-cropper': `<div class="settings-grid"><div class="field-group"><label class="field-label" for="crop-x">X</label><input class="tool-control" id="crop-x" type="number" min="0" value="0"><p class="field-helper">Left crop offset.</p></div><div class="field-group"><label class="field-label" for="crop-y">Y</label><input class="tool-control" id="crop-y" type="number" min="0" value="0"><p class="field-helper">Top crop offset.</p></div><div class="field-group"><label class="field-label" for="crop-w">Width</label><input class="tool-control" id="crop-w" type="number" min="1"><p class="field-helper">Crop width in pixels.</p></div><div class="field-group"><label class="field-label" for="crop-h">Height</label><input class="tool-control" id="crop-h" type="number" min="1"><p class="field-helper">Crop height in pixels.</p></div></div>`,
    'image-converter': `<div class="settings-grid"><div class="field-group"><label class="field-label" for="format">Output format</label><select class="tool-control" id="format"><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select><p class="field-helper">Choose the browser-supported output type.</p></div></div>`,
    'image-enhancer': `<div class="settings-grid"><div class="field-group"><label class="field-label" for="brightness">Brightness</label><input class="range-control" id="brightness" type="range" min="50" max="150" value="100"><p class="field-helper">Adjust overall lightness.</p></div><div class="field-group"><label class="field-label" for="contrast">Contrast</label><input class="range-control" id="contrast" type="range" min="50" max="150" value="105"><p class="field-helper">Increase or reduce tonal separation.</p></div><div class="field-group"><label class="field-label" for="saturation">Saturation</label><input class="range-control" id="saturation" type="range" min="0" max="200" value="110"><p class="field-helper">Control color intensity.</p></div><div class="field-group"><label class="field-label" for="sharpness">Sharpness</label><input class="range-control" id="sharpness" type="range" min="0" max="80" value="10"><p class="field-helper">Apply a subtle sharpening pass.</p></div></div>`,
    'image-rotator': `<div class="settings-grid"><div class="field-group"><label class="field-label" for="angle">Rotation angle</label><select class="tool-control" id="angle"><option value="90">90 degrees</option><option value="180">180 degrees</option><option value="270">270 degrees</option></select><p class="field-helper">Rotate clockwise before downloading.</p></div></div>`,
    'image-watermark': `<div class="settings-grid"><div class="field-group field-group-full"><label class="field-label" for="watermark">Watermark text</label><input class="tool-control" id="watermark" type="text" value="Image Tools"><p class="field-helper">The text is placed near the lower-right corner.</p></div></div>`,
    'metadata-remover': '<div class="settings-grid"><p class="alert-box">Canvas export re-encodes the visible pixels and strips most metadata such as EXIF information.</p></div>',
  };
  return map[slug] || map['image-converter'];
}

function dropzone(icon: string, title: string, text: string, multiple = false) { return `<label class="upload-drop block cursor-pointer rounded-2xl border-2 border-dashed border-indigo-200 bg-gray-50 p-6 text-center transition hover:border-indigo-400 focus-within:border-indigo-500 md:p-8"><div class="flex flex-col items-center gap-3"><i class="fa-solid ${icon} text-3xl text-gray-700" aria-hidden="true"></i><strong class="text-base font-semibold text-gray-900">${title}</strong><span class="text-sm text-gray-500">${text}</span></div><input data-file-input type="file" accept="image/*" ${multiple ? 'multiple' : ''} class="sr-only"></label>`; }
function pdfToImagePanel() { return `<section class="${section}"><div class="${wrap}"><div class="tool-layout" data-tool-root><div class="${card} tool-panel"><h2 class="${h2}">Main Tool Panel</h2><label class="upload-drop block cursor-pointer rounded-2xl border-2 border-dashed border-indigo-200 bg-gray-50 p-6 text-center transition hover:border-indigo-400 md:p-8"><div class="flex flex-col items-center gap-3"><i class="fa-solid fa-layer-group text-3xl text-gray-700" aria-hidden="true"></i><strong class="text-base font-semibold text-gray-900">Upload a PDF file</strong><span class="text-sm text-gray-500">Pages render locally to PNG images</span></div><input data-file-input type="file" accept="application/pdf" class="sr-only"></label><p class="alert-box" data-file-name>No file selected</p><div class="action-group"><button class="${btnPrimary}" data-action disabled>Render PDF Pages</button><button class="${btnSecondary}" data-reset>Reset</button></div><p class="text-sm font-medium text-indigo-700" data-status aria-live="polite">Choose a PDF to begin.</p><div class="grid grid-cols-1 gap-3 sm:grid-cols-3" data-stats><div class="result-box"><strong class="block text-gray-900">-</strong><span class="text-sm text-gray-500">Pages</span></div><div class="result-box"><strong class="block text-gray-900">-</strong><span class="text-sm text-gray-500">Rendered</span></div><div class="result-box"><strong class="block text-gray-900">-</strong><span class="text-sm text-gray-500">Format</span></div></div></div><aside class="${card} tool-panel"><h2 class="${h2}">Preview</h2><div class="preview-box" data-preview><span class="text-sm text-gray-500">Rendered PDF pages will appear here</span></div><div data-pdf-output class="space-y-4"></div></aside></div></div></section>`; }
function placeholder(message: string) { return `<section class="${section}"><div class="${wrap}"><div class="${card} tool-panel"><h2 class="${h2}">Main Tool Panel</h2><label class="upload-drop block rounded-2xl border-2 border-dashed border-indigo-200 bg-gray-50 p-8 text-center"><div class="flex flex-col items-center gap-3"><i class="fa-solid fa-layer-group text-3xl text-gray-700" aria-hidden="true"></i><strong class="text-base font-semibold text-gray-900">Prepared integration workspace</strong><span class="text-sm text-gray-500">This page is ready for a future client-side processor.</span></div><input type="file" disabled class="sr-only"></label><p class="alert-box">${message}</p><button class="${btnPrimary}" disabled>Integration Required</button></div></div></section>`; }
function info(slug: string, name: string, faqs: { question: string; answer: string }[]) { return `<section class="${section}"><div class="${wrap}"><div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3"><article class="${card} space-y-3"><h2 class="text-xl font-semibold text-gray-900">How to use this tool</h2><p class="ui-text">Upload a supported file, adjust the available settings, process the image, then download the result.</p></article><article class="${card} space-y-3"><h2 class="text-xl font-semibold text-gray-900">What this tool does</h2><p class="ui-text">${name} provides focused controls for a single image workflow with clear previews and download actions.</p></article><article class="${card} space-y-3"><h2 class="text-xl font-semibold text-gray-900">Privacy note</h2><p class="ui-text">Most implemented tools run locally in your browser. Placeholder tools are clearly labeled and do not fake processing.</p></article></div></div></section><section class="${section}"><div class="${wrap}"><h2 class="ui-section-title mb-5">Related Tools</h2><div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">${relatedTools(slug, 3).map((tool) => `<a data-link class="${card} ui-card-link flex min-h-full flex-col gap-3" href="/${tool.slug}"><span class="inline-flex h-10 w-10 items-center justify-center rounded-xl border border-indigo-200 bg-indigo-50 text-indigo-600"><i class="fa-solid ${tool.icon.includes(' ') ? 'fa-image' : tool.icon}" aria-hidden="true"></i></span><h3 class="text-lg font-semibold text-gray-900">${tool.name}</h3><p class="ui-text">${tool.description}</p></a>`).join('')}</div></div></section><section class="pb-14"><div class="${wrap}"><h2 class="ui-section-title mb-5">FAQ</h2><div class="space-y-4">${faqs.map((item) => `<article class="ui-card"><h3 class="font-semibold text-gray-900">${item.question}</h3><p class="ui-text mt-2">${item.answer}</p></article>`).join('')}</div></div></section>`; }
