import { getTool, relatedTools } from '../data/tools';
import { appSchema, faqSchema } from '../utils/seo';

export function toolPage(slug: string) {
  const tool = getTool(slug); if (!tool) return null;
  const faqs = [{ question: `How does ${tool.name} work?`, answer: tool.implemented ? 'The tool uses browser APIs where possible so the file can be processed on your device.' : 'This page is prepared for a future client-side integration and does not currently perform the final operation.' }, { question: 'Are files intentionally stored?', answer: 'No. This static website does not intentionally store your selected files.' }];
  return { seo: { title: `${tool.name} | Free Online Image Tool`, description: tool.description, path: `/${slug}`, jsonLd: [appSchema(tool.name, tool.description, `/${slug}`), faqSchema(faqs)] }, html: `<section class="page-hero site-container"><span class="icon-box"><i class="fa-solid ${tool.icon.includes(' ') ? 'fa-image' : tool.icon}" aria-hidden="true"></i></span><h1>${tool.name}</h1><p class="lead">${tool.description}</p><div class="trust-row"><span><i class="fa-solid fa-shield-halved" aria-hidden="true"></i> Privacy-aware workflow</span><span><i class="fa-solid fa-bolt" aria-hidden="true"></i> Browser-friendly</span><span><i class="fa-solid fa-mobile-screen-button" aria-hidden="true"></i> Responsive UI</span></div></section>${panel(slug)}${info(slug, tool.name, faqs)}` };
}

function panel(slug: string) {
  if (slug === 'pdf-to-image') return pdfToImagePanel();
  if (slug === 'background-remover') return placeholder('AI background removal is prepared for future integration.');
  if (slug === 'image-to-pdf') return `<section class="section"><div class="site-container"><div class="tool-panel" data-tool-root><h2>Main Tool Panel</h2><label class="dropzone"><i class="fa-solid fa-file-image fa-2x" aria-hidden="true"></i><strong>Upload or drop images</strong><span>JPG, PNG, or WebP</span><input data-file-input type="file" accept="image/*" multiple></label><ul data-file-list class="notice"><li>No images selected</li></ul><div class="settings"><div class="field"><label for="page-size">Page size</label><select id="page-size"><option value="auto">Auto</option><option value="a4">A4</option><option value="letter">Letter</option></select></div><div class="actions"><button class="btn btn-primary" data-action disabled>Generate PDF</button></div><p class="status" data-status aria-live="polite">Choose images to begin.</p></div></div></div></section>`;
  return `<section class="section"><div class="site-container"><div class="tool-grid" data-tool-root><div class="tool-panel"><h2>Main Tool Panel</h2><label class="dropzone"><i class="fa-solid fa-image fa-2x" aria-hidden="true"></i><strong>Upload or drop your image</strong><span>Accepted formats depend on this tool</span><input data-file-input type="file" accept="image/*"></label><p class="notice" data-file-name>No file selected</p>${settings(slug)}<div class="actions"><button class="btn btn-primary" data-action disabled>Process Image</button><button class="btn btn-secondary" data-download disabled><i class="fa-solid fa-download" aria-hidden="true"></i> Download</button><button class="btn btn-secondary" data-reset>Reset</button></div><p class="status" data-status aria-live="polite">Choose an image to begin.</p><div class="stats" data-stats><div class="stat"><strong>-</strong>Original</div><div class="stat"><strong>-</strong>Output</div><div class="stat"><strong>-</strong>Result</div></div></div><aside class="tool-panel"><h2>Preview</h2><div class="preview ${slug === 'image-cropper' ? 'cropper-wrap' : ''}" data-source-preview><span>Selected image preview</span></div><div class="preview" data-preview><span>Output preview will appear here</span></div></aside></div></div></section>`;
}

function settings(slug: string) {
  const map: Record<string, string> = {
    'image-compressor': '<div class="settings"><div class="field"><label for="quality">Quality percentage</label><input id="quality" type="range" min="10" max="100" value="78"></div><div class="field"><label for="format">Output format</label><select id="format"><option value="same">Same as input</option><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></div></div>',
    'image-resizer': '<div class="settings"><div class="field"><label for="width">Width</label><input id="width" type="number" min="1"></div><div class="field"><label for="height">Height</label><input id="height" type="number" min="1"></div><label class="check-row"><input id="ratio" type="checkbox" checked> Maintain aspect ratio</label></div>',
    'image-cropper': '<div class="settings grid grid-4"><div class="field"><label for="crop-x">X</label><input id="crop-x" type="number" min="0" value="0"></div><div class="field"><label for="crop-y">Y</label><input id="crop-y" type="number" min="0" value="0"></div><div class="field"><label for="crop-w">Width</label><input id="crop-w" type="number" min="1"></div><div class="field"><label for="crop-h">Height</label><input id="crop-h" type="number" min="1"></div></div>',
    'image-converter': '<div class="settings"><div class="field"><label for="format">Output format</label><select id="format"><option value="image/jpeg">JPG</option><option value="image/png">PNG</option><option value="image/webp">WebP</option></select></div></div>',
    'image-enhancer': '<div class="settings"><div class="field"><label for="brightness">Brightness</label><input id="brightness" type="range" min="50" max="150" value="100"></div><div class="field"><label for="contrast">Contrast</label><input id="contrast" type="range" min="50" max="150" value="105"></div><div class="field"><label for="saturation">Saturation</label><input id="saturation" type="range" min="0" max="200" value="110"></div><div class="field"><label for="sharpness">Sharpness</label><input id="sharpness" type="range" min="0" max="80" value="10"></div></div>',
    'image-rotator': '<div class="settings"><div class="field"><label for="angle">Rotation angle</label><select id="angle"><option value="90">90 degrees</option><option value="180">180 degrees</option><option value="270">270 degrees</option></select></div></div>',
    'image-watermark': '<div class="settings"><div class="field"><label for="watermark">Watermark text</label><input id="watermark" type="text" value="Image Tools"></div></div>',
    'metadata-remover': '<div class="settings"><p class="notice">Canvas export re-encodes the visible pixels and strips most metadata such as EXIF information.</p></div>',
  };
  return map[slug] || map['image-converter'];
}

function pdfToImagePanel() { return `<section class="section"><div class="site-container"><div class="tool-grid" data-tool-root><div class="tool-panel"><h2>Main Tool Panel</h2><label class="dropzone"><i class="fa-solid fa-layer-group fa-2x" aria-hidden="true"></i><strong>Upload a PDF file</strong><span>Pages render locally to PNG images</span><input data-file-input type="file" accept="application/pdf"></label><p class="notice" data-file-name>No file selected</p><div class="actions"><button class="btn btn-primary" data-action disabled>Render PDF Pages</button><button class="btn btn-secondary" data-reset>Reset</button></div><p class="status" data-status aria-live="polite">Choose a PDF to begin.</p><div class="stats" data-stats><div class="stat"><strong>-</strong>Pages</div><div class="stat"><strong>-</strong>Rendered</div><div class="stat"><strong>-</strong>Format</div></div></div><aside class="tool-panel"><h2>Preview</h2><div class="preview" data-preview><span>Rendered PDF pages will appear here</span></div><div data-pdf-output class="settings"></div></aside></div></div></section>`; }
function placeholder(message: string) { return `<section class="section"><div class="site-container"><div class="tool-panel"><h2>Main Tool Panel</h2><label class="dropzone"><i class="fa-solid fa-layer-group fa-2x" aria-hidden="true"></i><strong>Prepared integration workspace</strong><span>This page is ready for a future client-side processor.</span><input type="file" disabled></label><p class="notice">${message}</p><div class="actions"><button class="btn btn-primary" disabled>Integration Required</button></div></div></div></section>`; }
function info(slug: string, name: string, faqs: { question: string; answer: string }[]) { return `<section class="section"><div class="site-container"><div class="grid grid-3"><article class="info-card card"><h2>How to use this tool</h2><p>Upload a supported file, adjust the available settings, process the image, then download the result.</p></article><article class="info-card card"><h2>What this tool does</h2><p>${name} provides focused controls for a single image workflow with clear previews and download actions.</p></article><article class="info-card card"><h2>Privacy note</h2><p>Most implemented tools run locally in your browser. Placeholder tools are clearly labeled and do not fake processing.</p></article></div></div></section><section class="section"><div class="site-container"><h2 class="category-title">Related Tools</h2><div class="grid grid-3">${relatedTools(slug, 3).map((tool) => `<a data-link class="card" href="/${tool.slug}"><span class="icon-box"><i class="fa-solid ${tool.icon.includes(' ') ? 'fa-image' : tool.icon}" aria-hidden="true"></i></span><h3>${tool.name}</h3><p>${tool.description}</p></a>`).join('')}</div></div></section><section class="section"><div class="site-container"><h2 class="category-title">FAQ</h2><div>${faqs.map((item) => `<article class="faq-item"><h3>${item.question}</h3><p>${item.answer}</p></article>`).join('')}</div></div></section>`; }
